### PR TITLE
Fix downloading the teaser

### PR DESCRIPTION
**Pull request by darealshinji**

### CODE REVIEW

**Comment by agustincordes** [comment]
What do you mean with this pull request? Is it a problem with the Senscape website? I just tried downloading all three versions of the teaser and it works fine :)

**Comment by darealshinji** [comment]
The old URL used by the script doesn't work: http://files.asylumgame.com/Asylum_Teaser_Unix.zip
But the new one does: http://www.facethehorror.com/files/Asylum_Teaser_Unix.zip

**Comment by agustincordes** [comment]
Ah OK, I see now! Thanks for the fix!! :)

**Comment by darealshinji** [comment]
By the way I've uploaded the re-arranged Asylum teaser with new engine binaries (32 and 64 bit) for Linux on Google Drive: https://drive.google.com/file/d/0BxClEVSW8QykajViVXNwc0wxRG8/view?usp=sharing

The binaries are mostly self-contained and the game should run on most distributions by running `./start-game.sh`. Just in case you're interested.

**Comment by agustincordes** [comment]
That's great news, thank you so much for this! We honestly hadn't got time to maintain the source of the teaser, but thanks to you and others it's still perfectly playable with the latest version of the engine :)

In case you didn't know, we were forced to reimplement Asylum with Unity to include certain features, which is why development on Dagon C++ has been so slow. We haven't abandoned the engine, but it will be a while until I'm able to resume its development. So sorry about this :(

**Pull request merged**
